#ifndef FONTS_H_INCLUDED
#define FONTS_H_INCLUDED

const wxFont TITLE_FONT(16, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD, false, "Roboto");
const wxFont NORMAL_FONT(12, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_LIGHT, false, "Roboto");

#endif // FONTS_H_INCLUDED
